---
# tasks file for ansible-role-docker

# toDo:
  # Verify function

- name: Enabling docker-ce repository
  copy:
    src: docker-ce.repo
    dest: /etc/yum.repos.d/
    owner: root
    group: root
    mode: 0644

- name: Install docker-ce
  dnf:
    name:
      - docker-ce
      - docker-ce-cli
      - container.io 
    state: present

- name: Enable docker daemon
  systemd:
    enabled: yes
    name: docker

- name: Start docker daemon
  systemd:
    state: started
    name: docker
