---
# tasks file for docker
- name: Installing Docker (moby-engine) & docker-compose on Fedora
  dnf:
    name: 
    - moby-engine
    - docker-compose

- name: Enable Docker service
  systemd: 
    name: docker
    enabled: yes

- name: Check for existing cgroups configuration
  shell: grep "systemd.unified_cgroup_hierarchy=0" /etc/default/grub
  register: cgroups_grep
  failed_when: "cgroups_grep.rc == 2"

- name: Updating GRUB to enable cgroups v1
  lineinfile:
    state: present
    dest: /etc/default/grub
    backrefs: yes
    regexp: '^(GRUB_CMDLINE_LINUX=(?!.* audit)\"[^\"]+)(\".*)'
    line: '\1 systemd.unified_cgroup_hierarchy=0\2'
  when: cgroups_grep.stdout == ""

- name: Rebuild GRUB
  command: grub2-mkconfig

- name: Restart server
  reboot: 


- name: Create directory for building selinux-dockersock
  file:
    path: /data/selinux-dockersock
    state: directory

- name: Clone repo for selinux-dockersock
  git:
    repo: https://github.com/dpw/selinux-dockersock.git
    dest: /data/selinux-dockersock
    clone: yes

- name: Build selinux-dockersock
  shell: cd /data/selinux-dockersock && make